blank_issues_enabled: false

contact_links:
    - name: Asking Questions
      url: https://github.com/paperback-community/general-extensions/discussions/categories/q-a
      about: Use the Q&A Discussions section if you want to ask questions.
    - name: Code of Conduct
      url: https://github.com/paperback-community/general-extensions?tab=coc-ov-file#readme
      about: Please read the code of conduct before creating any issue.
    - name: Support Guidelines
      url: https://github.com/paperback-community/general-extensions/blob/master/.github/SUPPORT.md
      about: Please read the support guidelines before creating any issue.
    - name: Search the Issue Tracker
      url: https://github.com/paperback-community/general-extensions/issues
      about: Check to make sure there is not an issue already open that is related to yours.
    - name: Our Discord Server
      url: https://discord.gg/paperback-community
      about: You can contact us through our Discord server as well.
